---
title: "Geospatial Assignment 2"
output: 
  html_document:
    toc: true          # Enable table of contents
    toc_depth: 2       # Allow headings up to level 2
    number_sections: true # Number sections and subheadings
date: '`r Sys.Date()`'
author: "Irache Vergara, Gretchen Moulton, Viktoria Gagua, Daniela Guggenberger"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list = ls())

# Library
library(readxl)
library(sf)
library(ggplot2)
library(spData)
library(terra)
library(raster)
library(maps)
library(dplyr)
library(tidyr)
library(readr)
library(rnaturalearth)
library(rnaturalearthdata)
library(osmdata)
library(remotes)
library(RColorBrewer)
library(gridExtra)
library(gdistance)
```

## Part 2

We first load the populated places data and filter to get the top 10 populated places. 

```{r}
# First we will map to our file location on Github to extract the places and roads data
github_base <- "/vsicurl/https://raw.githubusercontent.com/Viktoriag27/Geospatial_Assignment_2/main/Data"

# Then we will store the natural earth data for places and roads
places <- st_read(paste0(github_base, "/ne_10m_populated_places_simple/ne_10m_populated_places_simple.shp"))
roads <- st_read(paste0(github_base, "/ne_10m_roads/ne_10m_roads.shp"))
```

Now that we have stored our data, we want to filter on the data for Spain. 
```{r}
# Filter for Spain for the 10 most populated places
top_10_spain <- places %>%
  filter(adm0name == "Spain") %>%  
  arrange(desc(pop_max)) %>%    
  head(10) 

# Print results to see which cities are the most populated
print(top_10_spain[, c("name", "pop_max")])

#We filter on just roads in Europe as there is no country variable for all countries in the roads dataframe
roads_euro <- roads %>%
  filter(continent=="Europe") 

# We need to get just the roads in Spain, so we first create an SF object of Spain
sf.spain <- world %>% 
  filter(iso_a2=='ES')

# Then we use this spatial object to perform a spatial intersection to get just the roads in Spain, not those outside of the country
roads_spain <- st_intersection(roads_euro, sf.spain)


# Finally we plot to see our work
plot(st_geometry(sf.spain), col = "azure2", border = "black")  
plot(st_geometry(roads_spain), col = "red", add = TRUE)  


```

Now let's work on building a raster/friction surface. First we need to convert Spain from vectors into a raster.
```{r}
# Let's get Spain in raster form
r.template <- rast(ext = ext(sf.spain), resolution = 0.05)

# Set the CRS to match Spain's CRS 
crs(r.template) <- crs(sf.spain)

# Now, assign a default value (e.g., 50) for friction to all the raster cells
values(r.template) <- 50  

# Then we need to rasterize the roads. We want to assign low friction to roads as they are easy to cross
roads_rast <- rasterize(vect(roads_spain), r.template, field = 5, update = TRUE)

# Replace missing values with a very small value to allow passage
vv <- values(r.template)  # Store values
vv[is.nan(vv)] <- 1/100   # Assign tiny friction to missing values
values(r.template) <- vv  # Assign back
rm(vv)

# Now we check our work by plotting
plot(roads_rast)

```

```{r}

# Using the (old) raster library for that:
sf.raster <- raster::raster(roads_rast)
sf.raster
rm(sf.raster)

tr.matrix <- transition(
  x = raster::raster(roads_rast),
  transitionFunction = mean,
  directions = 8
)

# Create a matrix to store shortest path distances
num_cities <- nrow(top_10_spain)
city_names <- top_10_spain$name

distance_matrix <- matrix(NA, nrow = num_cities, ncol = num_cities, 
                          dimnames = list(city_names, city_names))

# Convert cities to 'sp' SpatialPoints
sp_cities <- lapply(1:num_cities, function(i) as_Spatial(top_10_spain[i,]))

# Loop through each unique pair of cities
for (i in 1:(num_cities - 1)) {
  for (j in (i + 1):num_cities) {
    
    # Calculate shortest path
    sp.distance <- shortestPath(
      x = tr.matrix,
      origin = sp_cities[[i]],  
      goal = sp_cities[[j]],    
      output = "SpatialLines"
    )
    
    # Convert to 'sf' object for length calculation
    sp.distance_sf <- st_as_sf(sp.distance)
    
    # Ensure CRS consistency
    st_crs(sp.distance_sf) <- st_crs(top_10_spain)
    
    # Store the shortest path length
    path_length <- st_length(sp.distance_sf)
    distance_matrix[i, j] <- path_length
    distance_matrix[j, i] <- path_length  # Symmetric matrix
  }
}

# Print the distance matrix
print(distance_matrix)

```

```{r}
# Plot the map
plot(st_geometry(sf.spain), col = "azure2", border = "black")  # Plot the border of Spain

# Plot the roads in red
plot(st_geometry(roads_spain), col = "red", add = TRUE)  

# Plot the cities (use different symbols, e.g., small points)
plot(st_geometry(top_10_spain), pch = 20, col = "blue", add = TRUE)

# Loop through the distance matrix to plot the shortest paths
for (i in 1:(num_cities - 1)) {
  for (j in (i + 1):num_cities) {
    # Extract the shortest path line
    sp.distance <- shortestPath(
      x = tr.matrix,
      origin = sp_cities[[i]],  
      goal = sp_cities[[j]],    
      output = "SpatialLines"
    )
    
    # Convert to 'sf' object for easy plotting
    sp.distance_sf <- st_as_sf(sp.distance)
    
    # Plot the shortest path (in black or any color of your choice)
    plot(st_geometry(sp.distance_sf), col = "black", add = TRUE)
  }
}

# You can also add labels to the cities for clarity
text(st_coordinates(top_10_spain), labels = top_10_spain$name, col = "blue", cex = 0.7, pos = 4)


```




